name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main  # puedes cambiarlo si usas 'dev'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/hello-world-server:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/hello-world-server:latest
